### PR TITLE
Set up repo to white-label Platform.Bible

### PR DESCRIPTION
**Pull request by tjcouch-sil**
Relates to https://github.com/paranext/paranext-core/issues/951. Will fork to make Paratext 10 Studio

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paranext/21)

### CODE REVIEW

**Review by lyonsil — CHANGES_REQUESTED** [review]
Two things:
1. It would be lovely to not have similar, but different configs for eslint, cspell, etc. compared to `paranext-core` show up here. 
2. I noticed on my initial `npm install` that there were several warnings:
```
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
```

Not a blocker, but if there is an easy way to resolve these it would be nice.

> Reviewed 34 of 36 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext/21#-:-O1T_lMx4Q1s0nfCqutx:b-sn694s)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @tjcouch-sil)

___
*[`package.json` line 2 at r2](https://reviewable.io/reviews/paranext/paranext/21#-O1Sm7vE6ZuzMVtfPSEi:-O1Sm7vE6ZuzMVtfPSEj:bm3l6ds) ([raw file](https://github.com/paranext/paranext/blob/481247257a882be23bddbf884c7b70b17d9030c0/package.json#L2)):*
> ```JSON
> {
>   "name": "platform.bible",
> ```

I cloned this branch and ran `npm install`. To my surprise `package-lock.json` changed to insert `platform.bible in place of 'paratext-10-studio`. Is that expected?
___
*[`README.md` line 188 at r2](https://reviewable.io/reviews/paranext/paranext/21#-O1TWUjf41lYiaFOY6ED:-O1TWUjf41lYiaFOY6EE:b-dvjm0u) ([raw file](https://github.com/paranext/paranext/blob/481247257a882be23bddbf884c7b70b17d9030c0/README.md#L188)):*
> ```Markdown
> 4. Update `CHANGELOG.md` with changes in this release from the GitHub draft **Release**.
> 5. Commit these changes to your release branch and push the commit to GitHub.
> 6. Once the GitHub build **Action** has finished, it will add build artifact files to the draft release. Remove the `.blockmap` files and leave the `.yml` files and the installers and executable, e.g. `.exe` on Windows.
> ```

I don't know why we say to remove the `.blockmap` files. It doesn't hurt anything to leave them there AFAIK.
___
*[`lib/build.util.ts` line 77 at r1](https://reviewable.io/reviews/paranext/paranext/21#gh-1672626963:-O1T_2d53xxLdGDvyu7K:b-fhyfqc) ([raw file](https://github.com/paranext/paranext/blob/d2ceddbdef93f5432c9e9da4b703d6c1d97eec3b/lib/build.util.ts#L77)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Shell command built from environment values

This shell command depends on an uncontrolled [absolute path](1).
This shell command depends on an uncontrolled [absolute path](2).

[Show more details](https://github.com/paranext/paranext/security/code-scanning/1)
</blockquote></details>

Even if this is benign, I think the error is going to pop up for others when they fork the repo and make changes. So we should probably spend the time to fix this to avoid having others sink time into worrying about it.

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext/21)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot])

___
*[`README.md` line 188 at r2](https://reviewable.io/reviews/paranext/paranext/21#-O1TWUjf41lYiaFOY6ED:-O1TbWB77Hc1HkU9pKkm:b-5me5id) ([raw file](https://github.com/paranext/paranext/blob/481247257a882be23bddbf884c7b70b17d9030c0/README.md#L188)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I don't know why we say to remove the `.blockmap` files. It doesn't hurt anything to leave them there AFAIK.
</blockquote></details>

This is copied over from `paranext-core`. I have no opinion, so I can remove this line in both if you'd like.
___
*[`lib/build.util.ts` line 77 at r1](https://reviewable.io/reviews/paranext/paranext/21#gh-1672626963:-O1Tc77c5DTfQVu34t07:b-v0ni20) ([raw file](https://github.com/paranext/paranext/blob/d2ceddbdef93f5432c9e9da4b703d6c1d97eec3b/lib/build.util.ts#L77)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

Even if this is benign, I think the error is going to pop up for others when they fork the repo and make changes. So we should probably spend the time to fix this to avoid having others sink time into worrying about it.
</blockquote></details>

Good point, though my pea brain isn't comprehending how to fix this. Is it just saying I need to put quotes around paths passed in? A bad actor could just put quotes in the command and do whatever they wanted... :thinking: It seems like it's almost saying I need to sanitize the command somehow, but it doesn't give a list of characters that are dangerous. I dunno. Any ideas? Can talk on a call instead of typing if desired. Working on reviewing your PR though, so not right now ;)

**Review by tjcouch-sil — COMMENTED** [review]
Regarding 1, I think we are having some conversations in other places about how to address this growing problem. I'd say that would probably be scoped to a separate issue personally.

Regarding 2, I don't see those warnings on running `npm i`, but I guess that's for some reason because it only shows them when the package first gets installed...? Seems weird. Anyway I discovered some things:

- `inflight@1.0.6` is a deep dependency of a bunch of packages in both `paranext-core` and `paranext`. Particularly in `paranext`, `eslint-config-erb@4.1.0` (latest) has the dependency `jest@29.7.0` (latest) which goes down 4 more steps to get to `inflight@1.0.6`.
- `@humanwhocodes/config-array` is a dependency of eslint@8.x.x and is the same in `paranext-core` and `paranext`. Unfortunately, one of the configs we use for eslint is not compatible with eslint@9.x.x (which uses `@eslint/config-array`). Here's the issue on making it compatible https://github.com/airbnb/javascript/issues/2961
- `rimraf@3.0.2` is a dependency of a number of packages in both `paranext-core` and `paranext`; however, we are doing all we can in our code to use a supported version (so we're using `5.0.7`. Particularly, `eslint@8.x.x` is stuck on `3.0.2` via a deep dependency. `eslint@9.x.x` would work fine)
- `glob@7.2.3` is pretty much the same story as `rimraf@3.0.2`
- `@humanwhocodes/object-schema` is basically the same story as the other `humanwhocodes` package

So unfortunately it looks like all those packages are stuck right now unless you have ideas for me :/ Yay npm dependencies :tada: love to see it

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext/21#-:-O1TgCEA-TkycNaH1Np5:b-lucbpd)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot] and @lyonsil)

___
*[`package.json` line 2 at r2](https://reviewable.io/reviews/paranext/paranext/21#-O1Sm7vE6ZuzMVtfPSEi:-O1TkOJV0qo9vPK-9cvT:b-2w6bx3) ([raw file](https://github.com/paranext/paranext/blob/481247257a882be23bddbf884c7b70b17d9030c0/package.json#L2)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

I cloned this branch and ran `npm install`. To my surprise `package-lock.json` changed to insert `platform.bible in place of 'paratext-10-studio`. Is that expected?
</blockquote></details>

Ah yeah, thanks. I forgot. Will fix

**Review by lyonsil — COMMENTED** [review]
Yes, I mentioned 1 since we've been talking about it but didn't expect it to be resolved here. Thanks for digging into 2! I don't have any better ideas for now. I just figured now was the time to bring it up.

> *[Reviewable](https://reviewable.io/reviews/paranext/paranext/21#-:-O1TpVfX8uAmAPzNWcgz:b-r0ydex)* status: all files reviewed, 2 unresolved discussions (waiting on @github-advanced-security[bot])

**Review by tjcouch-sil — COMMENTED** [review]
> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext/21)* status: 32 of 36 files reviewed, 1 unresolved discussion (waiting on @lyonsil)

___
*[`package.json` line 2 at r2](https://reviewable.io/reviews/paranext/paranext/21#-O1Sm7vE6ZuzMVtfPSEi:-O1XR_n05PuetrKXOpM0:bt2vr1b) ([raw file](https://github.com/paranext/paranext/blob/481247257a882be23bddbf884c7b70b17d9030c0/package.json#L2)):*
<details><summary><i>Previously, tjcouch-sil (TJ Couch) wrote…</i></summary><blockquote>

Ah yeah, thanks. I forgot. Will fix
</blockquote></details>

Fixed.
___
*[`lib/build.util.ts` line 77 at r1](https://reviewable.io/reviews/paranext/paranext/21#gh-1672626963:-O1XRMhEAr5lG2nHebpN:b-bi3as2) ([raw file](https://github.com/paranext/paranext/blob/d2ceddbdef93f5432c9e9da4b703d6c1d97eec3b/lib/build.util.ts#L77)):*
<details><summary><i>Previously, lyonsil (Matt Lyons) wrote…</i></summary><blockquote>

[Here is some documentation](https://codeql.github.com/codeql-query-help/javascript/js-shell-command-injection-from-environment/) about this error/warning. It doesn't like how you're using `path` to set the working directory.
</blockquote></details>

Thanks for the help!

GitHub has marked this security alert as fixed: https://github.com/paranext/paranext/security/code-scanning/1

Force resolving this comment because Reviewable doesn't pick this up.

**Review by lyonsil — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paranext/21#-:-O1Xf_y6-tKc3tS48esl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
